language: node_js
before_install:
  # g++
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi


install:
  # g++4.8.1
  - if [ "$CXX" == "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" == "g++" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50; fi

  # Update cmake: 
  - wget http://www.cmake.org/files/v3.0/cmake-3.0.1-Linux-i386.tar.gz
  - tar -xzf cmake-3.0.1-Linux-i386.tar.gz
  - sudo cp -fR cmake-3.0.1-Linux-i386/* /usr
  - rm -rf cmake-3.0.1-Linux-i386
  - rm cmake-3.0.1-Linux-i386.tar.gz

  #Configure cmake compiler
  - export TRAVIS_CXX=$CXX

  - sudo apt-get install build-essential
  - curl -sL https://github.com/Itseez/opencv/archive/3.0.0-alpha.zip > opencv.zip
  - unzip opencv.zip
  - rm opencv.zip
  - mkdir opencv-build
  - cd opencv-build/
  - cmake -DCMAKE_BUILD_TYPE=RELEASE -DBUILD_DOCS=OFF -DBUILD_EXAMPLES=OFF -DBUILD_opencv_java=OFF -DBUILD_JASPER=OFF -DWITH_JASPER=OFF -DBUILD_ZLIB=ON -DBUILD_SHARED_LIBS=OFF -DBUILD_TESTS=OFF -DBUILD_PERF_TESTS=OFF -DWITH_OPENEXR=OFF -DBUILD_PNG=ON -DWITH_PNG=ON -DWITH_TIFF=OFF -DBUILD_TIFF=OFF -DWITH_WEBP=OFF -DWITH_JPEG=ON -DBUILD_JPEG=ON ../opencv-3.0.0-alpha/
  - sudo make install
  - cd ..
  - npm install nan

script: 
  # Show me what compiler are you using:
  - echo $TRAVIS_CXX
  - $TRAVIS_CXX --version

  - cmake --version

  - if [ "$CXX" == "clang++" ]; then export CXX="clang++" && bii cpp:build; fi
  - if [ "$CXX" == "g++" ];     then export CXX="g++"     && bii cpp:build; fi
